// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdcrvyyxtmtdfyhtamvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkY3J2eXl4dG10ZGZ5aHRhbXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjE2MzMsImV4cCI6MjA2MTMzNzYzM30.dzqWtQCQ5tBKBKU33PuThyI8_lOt1eXEN4hbgzL4THA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);